#pragma once
#include <Geode/binding/PlayerObject.hpp>
#include <Geode/binding/PlayerCheckpoint.hpp>
#include <Geode/binding/PlayLayer.hpp>
#include <Geode/binding/GameObject.hpp>
#include <Geode/binding/DashRingObject.hpp>

using namespace geode::prelude;

struct SupplementalPlayerState {
    double m_yVelocity = 0.0;
    double m_platformerXVelocity = 0.0;
    bool m_isOnGround = false;
    cocos2d::CCPoint m_lastPortalPos = {};
    GameObject* m_lastActivatedPortal = nullptr;
    cocos2d::CCPoint m_lastGroundedPos = {};
    bool m_isDashing = false;
    DashRingObject* m_dashRing = nullptr;
    double m_lastLandTime = 0.0;
    bool m_isAccelerating = false;
    bool m_affectedByForces = false;
    float m_rotationSpeed = 0.0f;
    bool m_isRotating = false;
    bool m_isBallRotating = false;
    bool m_isBallRotating2 = false;
    bool m_jumpHeld = false;
    bool m_stateRingJump = false;
    bool m_touchedPad = false;
    bool m_isMoving = false;
    bool m_holdingRight = false;
    bool m_holdingLeft = false;
    bool m_leftPressedFirst = false;
    bool m_platformerMovingLeft = false;
    bool m_platformerMovingRight = false;
    bool m_wasTeleported = false;
    bool m_fixGravityBug = false;
    bool m_reverseSync = false;
    double m_yVelocityBeforeSlope = 0.0;
    double m_dashX = 0.0;
    double m_dashY = 0.0;
    double m_dashAngle = 0.0;
    double m_dashStartTime = 0.0;
    double m_slopeStartTime = 0.0;
    bool m_justPlacedStreak = false;
    int m_lastCollisionBottom = 0;
    int m_lastCollisionTop = 0;
    int m_lastCollisionLeft = 0;
    int m_lastCollisionRight = 0;
    bool m_jumpBuffered = false;
    int m_unk50C = 0;
    int m_unk510 = 0;
    GameObject* m_currentSlope2 = nullptr;
    GameObject* m_preLastGroundObject = nullptr;
    float m_slopeAngle = 0.0f;
    bool m_slopeSlidingMaybeRotated = false;
    bool m_quickCheckpointMode = false;
    GameObject* m_collidedObject = nullptr;
    GameObject* m_lastGroundObject = nullptr;
    GameObject* m_collidingWithLeft = nullptr;
    GameObject* m_collidingWithRight = nullptr;
    double m_scaleXRelated2 = 0.0;
    double m_groundYVelocity = 0.0;
    double m_yVelocityRelated = 0.0;
    double m_scaleXRelated3 = 0.0;
    double m_scaleXRelated4 = 0.0;
    double m_scaleXRelated5 = 0.0;
    bool m_isCollidingWithSlope = false;
    bool m_unk669 = false;
    GameObject* m_currentPotentialSlope = nullptr;
    GameObject* m_currentSlope = nullptr;
    double unk_584 = 0.0;
    int m_collidingWithSlopeId = 0;
    bool m_slopeFlipGravityRelated = false;
    float m_slopeAngleRadians = 0.0f;
    float m_rotateSpeed = 0.0f;
    double m_speedMultiplier = 0.0;
    double m_yStart = 0.0;
    double m_gravity = 0.0;
    float m_trailingParticleLife = 0.0f;
    double m_gameModeChangedTime = 0.0;
    bool m_padRingRelated = false;
    bool m_maybeIsFalling = false;
    bool m_shouldTryPlacingCheckpoint = false;
    bool m_playEffects = false;
    bool m_isOnGround3 = false;
    double m_lastSpiderFlipTime = 0.0;
    bool m_unkBool5 = false;
    double m_accelerationOrSpeed = 0.0;
    double m_snapDistance = 0.0;
    bool m_ringJumpRelated = false;
    GameObject* m_objectSnappedTo = nullptr;
    bool m_maybeSpriteRelated = false;
    float m_landParticlesAngle = 0.0f;
    float m_landParticleRelatedY = 0.0f;
    double m_slopeRotation = 0.0;
    double m_currentSlopeYVelocity = 0.0;
    double m_unk3d0 = 0.0;
    double m_blackOrbRelated = 0.0;
    bool m_unk3e0 = false;
    bool m_unk3e1 = false;
    bool m_isCurrentSlopeTop = false;
    double m_collidedTopMinY = 0.0;
    double m_collidedBottomMaxY = 0.0;
    double m_collidedLeftMaxX = 0.0;
    double m_collidedRightMinX = 0.0;
    bool m_wasJumpBuffered = false;
    bool m_wasRobotJump = false;
    unsigned char m_stateJumpBuffered = 0;
    bool m_stateRingJump2 = false;
    bool m_touchedRing = false;
    bool m_touchedCustomRing = false;
    bool m_touchedGravityPortal = false;
    bool m_maybeTouchedBreakableBlock = false;
    double m_fallSpeed = 0.0;
    bool m_isOnSlope = false;
    bool m_wasOnSlope = false;
    float m_slopeVelocity = 0.0f;
    bool m_maybeUpsideDownSlope = false;
    int m_reverseRelated = 0;
    double m_maybeReverseSpeed = 0.0;
    double m_maybeReverseAcceleration = 0.0;
    float m_xVelocityRelated2 = 0.0f;
    bool m_isOnGround2 = false;
    float m_platformerVelocityRelated = 0.0f;
    bool m_maybeIsBoosted = false;
    double m_scaleXRelatedTime = 0.0;
    bool m_decreaseBoostSlide = false;
    bool m_isLocked = false;
    bool m_controlsDisabled = false;
    float m_yVelocityRelated3 = 0.0f;
    bool m_defaultMiniIcon = false;
    bool m_swapColors = false;
    bool m_switchDashFireColor = false;
    int m_followRelated = 0;
    float m_unk838 = 0.0f;
    int m_stateOnGround = 0;
    unsigned char m_stateUnk = 0;
    unsigned char m_stateNoStickX = 0;
    unsigned char m_stateNoStickY = 0;
    unsigned char m_stateUnk2 = 0;
    int m_stateBoostX = 0;
    int m_stateBoostY = 0;
    int m_maybeStateForce2 = 0;
    int m_stateScale = 0;
    double m_scaleXRelated = 0.0;
    bool m_maybeHasStopped = false;
    float m_xVelocityRelated = 0.0f;
    bool m_maybeGoingCorrectSlopeDirection = false;
    bool m_isSliding = false;
    double m_maybeSlopeForce = 0.0;
    bool m_isOnIce = false;
    double m_physDeltaRelated = 0.0;
    bool m_isOnGround4 = false;
    int m_maybeSlidingTime = 0;
    double m_maybeSlidingStartTime = 0.0;
    double m_changedDirectionsTime = 0.0;
    double m_slopeEndTime = 0.0;
    bool m_isSlidingRight = false;
    double m_maybeChangedDirectionAngle = 0.0;
    int m_stateNoAutoJump = 0;
    int m_stateDartSlide = 0;
    int m_stateHitHead = 0;
    int m_stateFlipGravity = 0;
    float m_gravityMod = 0.0f;
    int m_stateForce = 0;
    cocos2d::CCPoint m_stateForceVector = {};
    float m_somethingPlayerSpeedTime = 0.0f;
    float m_playerSpeedAC = 0.0f;
    bool m_fixRobotJump = false;
    bool m_inputsLocked = false;
    float m_fallStartY = 0.0f;
    double m_lastLandTime2 = 0.0;
    bool m_isGoingLeft = false;
    float m_vehicleSize = 1.0f;
    float m_playerSpeed = 0.0f;
    cocos2d::CCPoint m_shipRotation = {};
    float m_unkUnused3 = 0.0f;
    bool m_maybeReverseAccel = false;
    int m_groundObjectMaterial = 0;
    bool m_isOutOfBounds = false;
    bool m_isRobot = false;
    bool m_isSpider = false;
    bool m_isBall = false;
    bool m_isShip = false;
    bool m_isBird = false;
    bool m_isDart = false;
    bool m_isSwing = false;
    bool m_isUpsideDown = false;
    bool m_isSideways = false;
    bool m_isHidden = false;
    std::array<bool, 4> m_holdingButtons = {};
    double m_lastFlipTime = 0.0;
    bool m_hasGlow = false;
    int m_dashFireFrame = 0;
    double m_positionX = 0.0;
    double m_positionY = 0.0;
    float m_rotation = 0.0f;

    #ifndef GEODE_IS_ANDROID
    std::unordered_map<int, GJPointDouble> m_rotateObjectsRelated;
    std::unordered_map<int, GameObject*> m_potentialSlopeMap;
    std::unordered_set<int> m_ringRelatedSet;
    std::unordered_set<int> m_touchedRings;
    std::map<int, bool> m_jumpPadRelated;
    std::vector<float> m_playerFollowFloats;
    std::vector<CCObject*> m_touchingRings;
    std::string m_currentRobotAnimation;
    #endif

    SupplementalPlayerState() = default;

    SupplementalPlayerState(PlayerObject* p) {
        if (!p) return;
        m_yVelocity                     = p->m_yVelocity;
        m_platformerXVelocity           = p->m_platformerXVelocity;
        m_isOnGround                    = p->m_isOnGround;
        m_lastPortalPos                 = p->m_lastPortalPos;
        m_lastActivatedPortal           = p->m_lastActivatedPortal;
        m_lastGroundedPos               = p->m_lastGroundedPos;
        m_isDashing                     = p->m_isDashing;
        m_dashRing                      = p->m_dashRing;
        m_jumpBuffered                  = p->m_jumpBuffered;
        m_lastLandTime                  = p->m_lastLandTime;
        m_isAccelerating                = p->m_isAccelerating;
        m_affectedByForces              = p->m_affectedByForces;
        m_rotationSpeed                 = p->m_rotationSpeed;
        m_isRotating                    = p->m_isRotating;
        m_isBallRotating                = p->m_isBallRotating;
        m_isBallRotating2               = p->m_isBallRotating2;
        m_stateRingJump                 = p->m_stateRingJump;
        m_touchedPad                    = p->m_touchedPad;
        m_isMoving                      = p->m_isMoving;
        m_holdingRight                  = p->m_holdingRight;
        m_holdingLeft                   = p->m_holdingLeft;
        m_leftPressedFirst              = p->m_leftPressedFirst;
        m_platformerMovingLeft          = p->m_platformerMovingLeft;
        m_platformerMovingRight         = p->m_platformerMovingRight;
        m_wasTeleported                 = p->m_wasTeleported;
        m_fixGravityBug                 = p->m_fixGravityBug;
        m_reverseSync                   = p->m_reverseSync;
        m_yVelocityBeforeSlope          = p->m_yVelocityBeforeSlope;
        m_dashX                         = p->m_dashX;
        m_dashY                         = p->m_dashY;
        m_dashAngle                     = p->m_dashAngle;
        m_dashStartTime                 = p->m_dashStartTime;
        m_slopeStartTime                = p->m_slopeStartTime;
        m_justPlacedStreak              = p->m_justPlacedStreak;
        m_lastCollisionBottom           = p->m_lastCollisionBottom;
        m_lastCollisionTop              = p->m_lastCollisionTop;
        m_lastCollisionLeft             = p->m_lastCollisionLeft;
        m_lastCollisionRight             = p->m_lastCollisionRight;
        m_unk50C                        = p->m_unk50C;
        m_unk510                        = p->m_unk510;
        m_currentSlope2                 = p->m_currentSlope2;
        m_preLastGroundObject           = p->m_preLastGroundObject;
        m_slopeAngle                    = p->m_slopeAngle;
        m_slopeSlidingMaybeRotated      = p->m_slopeSlidingMaybeRotated;
        m_quickCheckpointMode           = p->m_quickCheckpointMode;
        m_collidedObject                = p->m_collidedObject;
        m_lastGroundObject              = p->m_lastGroundObject;
        m_collidingWithLeft             = p->m_collidingWithLeft;
        m_collidingWithRight            = p->m_collidingWithRight;
        m_scaleXRelated2                = p->m_scaleXRelated2;
        m_groundYVelocity               = p->m_groundYVelocity;
        m_yVelocityRelated              = p->m_yVelocityRelated;
        m_scaleXRelated3                = p->m_scaleXRelated3;
        m_scaleXRelated4                = p->m_scaleXRelated4;
        m_scaleXRelated5                = p->m_scaleXRelated5;
        m_isCollidingWithSlope          = p->m_isCollidingWithSlope;
        m_unk669                        = p->m_unk669;
        m_currentPotentialSlope         = p->m_currentPotentialSlope;
        m_currentSlope                  = p->m_currentSlope;
        unk_584                         = p->unk_584;
        m_collidingWithSlopeId          = p->m_collidingWithSlopeId;
        m_slopeFlipGravityRelated       = p->m_slopeFlipGravityRelated;
        m_slopeAngleRadians             = p->m_slopeAngleRadians;
        m_rotateSpeed                   = p->m_rotateSpeed;
        m_speedMultiplier               = p->m_speedMultiplier;
        m_yStart                        = p->m_yStart;
        m_gravity                       = p->m_gravity;
        m_trailingParticleLife          = p->m_trailingParticleLife;
        m_gameModeChangedTime           = p->m_gameModeChangedTime;
        m_padRingRelated                = p->m_padRingRelated;
        m_maybeIsFalling                = p->m_maybeIsFalling;
        m_shouldTryPlacingCheckpoint    = p->m_shouldTryPlacingCheckpoint;
        m_playEffects                   = p->m_playEffects;
        m_isOnGround3                   = p->m_isOnGround3;
        m_lastSpiderFlipTime            = p->m_lastSpiderFlipTime;
        m_unkBool5                      = p->m_unkBool5;
        m_accelerationOrSpeed           = p->m_accelerationOrSpeed;
        m_snapDistance                  = p->m_snapDistance;
        m_ringJumpRelated               = p->m_ringJumpRelated;
        m_objectSnappedTo               = p->m_objectSnappedTo;
        m_maybeSpriteRelated            = p->m_maybeSpriteRelated;
        m_landParticlesAngle            = p->m_landParticlesAngle;
        m_landParticleRelatedY          = p->m_landParticleRelatedY;
        m_slopeRotation                 = p->m_slopeRotation;
        m_currentSlopeYVelocity         = p->m_currentSlopeYVelocity;
        m_unk3d0                        = p->m_unk3d0;
        m_blackOrbRelated               = p->m_blackOrbRelated;
        m_unk3e0                        = p->m_unk3e0;
        m_unk3e1                        = p->m_unk3e1;
        m_isCurrentSlopeTop             = p->m_isCurrentSlopeTop;
        m_collidedTopMinY               = p->m_collidedTopMinY;
        m_collidedBottomMaxY            = p->m_collidedBottomMaxY;
        m_collidedLeftMaxX              = p->m_collidedLeftMaxX;
        m_collidedRightMinX             = p->m_collidedRightMinX;
        m_wasJumpBuffered               = p->m_wasJumpBuffered;
        m_wasRobotJump                  = p->m_wasRobotJump;
        m_stateJumpBuffered             = p->m_stateJumpBuffered;
        m_stateRingJump2                = p->m_stateRingJump2;
        m_touchedRing                   = p->m_touchedRing;
        m_touchedCustomRing             = p->m_touchedCustomRing;
        m_touchedGravityPortal          = p->m_touchedGravityPortal;
        m_maybeTouchedBreakableBlock    = p->m_maybeTouchedBreakableBlock;
        m_fallSpeed                     = p->m_fallSpeed;
        m_isOnSlope                     = p->m_isOnSlope;
        m_wasOnSlope                    = p->m_wasOnSlope;
        m_slopeVelocity                 = p->m_slopeVelocity;
        m_maybeUpsideDownSlope          = p->m_maybeUpsideDownSlope;
        m_reverseRelated                = p->m_reverseRelated;
        m_maybeReverseSpeed             = p->m_maybeReverseSpeed;
        m_maybeReverseAcceleration      = p->m_maybeReverseAcceleration;
        m_xVelocityRelated2             = p->m_xVelocityRelated2;
        m_isOnGround2                   = p->m_isOnGround2;
        m_platformerVelocityRelated     = p->m_platformerVelocityRelated;
        m_maybeIsBoosted                = p->m_maybeIsBoosted;
        m_scaleXRelatedTime             = p->m_scaleXRelatedTime;
        m_decreaseBoostSlide            = p->m_decreaseBoostSlide;
        m_isLocked                      = p->m_isLocked;
        m_controlsDisabled              = p->m_controlsDisabled;
        m_yVelocityRelated3             = p->m_yVelocityRelated3;
        m_defaultMiniIcon               = p->m_defaultMiniIcon;
        m_swapColors                    = p->m_swapColors;
        m_switchDashFireColor           = p->m_switchDashFireColor;
        m_followRelated                 = p->m_followRelated;
        m_unk838                        = p->m_unk838;
        m_stateOnGround                 = p->m_stateOnGround;
        m_stateUnk                      = p->m_stateUnk;
        m_stateNoStickX                 = p->m_stateNoStickX;
        m_stateNoStickY                 = p->m_stateNoStickY;
        m_stateUnk2                     = p->m_stateUnk2;
        m_stateBoostX                   = p->m_stateBoostX;
        m_stateBoostY                   = p->m_stateBoostY;
        m_maybeStateForce2              = p->m_maybeStateForce2;
        m_stateScale                    = p->m_stateScale;
        m_scaleXRelated                 = p->m_scaleXRelated;
        m_maybeHasStopped               = p->m_maybeHasStopped;
        m_xVelocityRelated              = p->m_xVelocityRelated;
        m_maybeGoingCorrectSlopeDirection = p->m_maybeGoingCorrectSlopeDirection;
        m_isSliding                     = p->m_isSliding;
        m_maybeSlopeForce               = p->m_maybeSlopeForce;
        m_isOnIce                       = p->m_isOnIce;
        m_physDeltaRelated              = p->m_physDeltaRelated;
        m_isOnGround4                   = p->m_isOnGround4;
        m_maybeSlidingTime              = p->m_maybeSlidingTime;
        m_maybeSlidingStartTime         = p->m_maybeSlidingStartTime;
        m_changedDirectionsTime         = p->m_changedDirectionsTime;
        m_slopeEndTime                  = p->m_slopeEndTime;
        m_isSlidingRight                = p->m_isSlidingRight;
        m_maybeChangedDirectionAngle    = p->m_maybeChangedDirectionAngle;
        m_stateNoAutoJump               = p->m_stateNoAutoJump;
        m_stateDartSlide                = p->m_stateDartSlide;
        m_stateHitHead                  = p->m_stateHitHead;
        m_stateFlipGravity              = p->m_stateFlipGravity;
        m_gravityMod                    = p->m_gravityMod;
        m_stateForce                    = p->m_stateForce;
        m_stateForceVector              = p->m_stateForceVector;
        m_somethingPlayerSpeedTime      = p->m_somethingPlayerSpeedTime;
        m_playerSpeedAC                 = p->m_playerSpeedAC;
        m_fixRobotJump                  = p->m_fixRobotJump;
        m_inputsLocked                  = p->m_inputsLocked;
        m_fallStartY                    = p->m_fallStartY;
        m_isGoingLeft                   = p->m_isGoingLeft;
        m_vehicleSize                   = p->m_vehicleSize;
        m_playerSpeed                   = p->m_playerSpeed;
        m_shipRotation                  = p->m_shipRotation;
        m_unkUnused3                    = p->m_unkUnused3;
        m_groundObjectMaterial          = p->m_groundObjectMaterial;
        m_isOutOfBounds                 = p->m_isOutOfBounds;
        m_isRobot                       = p->m_isRobot;
        m_isSpider                      = p->m_isSpider;
        m_isBall                        = p->m_isBall;
        m_isShip                        = p->m_isShip;
        m_isBird                        = p->m_isBird;
        m_isDart                        = p->m_isDart;
        m_isSwing                       = p->m_isSwing;
        m_isUpsideDown                  = p->m_isUpsideDown;
        m_isSideways                    = p->m_isSideways;
        m_isHidden                      = p->m_isHidden;
        for (size_t i = 1; i < m_holdingButtons.size(); i++)
            m_holdingButtons[i] = p->m_holdingButtons[i];
        m_lastFlipTime                  = p->m_lastFlipTime;
        m_hasGlow                       = p->m_hasGlow;
        m_dashFireFrame                 = p->m_dashFireFrame;
        m_positionX                     = p->m_positionX;
        m_positionY                     = p->m_positionY;
        m_rotation                      = p->getRotation();

        #ifndef GEODE_IS_ANDROID
        m_rotateObjectsRelated          = p->m_rotateObjectsRelated;
        m_potentialSlopeMap             = p->m_potentialSlopeMap;
        m_ringRelatedSet                = p->m_ringRelatedSet;
        m_touchedRings                  = p->m_touchedRings;
        m_jumpPadRelated                = p->m_jumpPadRelated;
        m_playerFollowFloats            = p->m_playerFollowFloats;
        m_currentRobotAnimation         = p->m_currentRobotAnimation;
        m_touchingRings.clear();
        for (int i = 0; i < p->m_touchingRings->count(); i++)
            m_touchingRings.push_back(p->m_touchingRings->objectAtIndex(i));
        #endif
    }

    void apply(PlayerObject* p) const {
        if (!p) return;
        p->m_platformerXVelocity            = m_platformerXVelocity;
        p->m_isOnGround                     = m_isOnGround;
        p->m_lastPortalPos                  = m_lastPortalPos;
        p->m_lastActivatedPortal            = m_lastActivatedPortal;
        p->m_lastGroundedPos                = m_lastGroundedPos;
        p->m_lastLandTime                   = m_lastLandTime;
        p->m_isAccelerating                 = m_isAccelerating;
        p->m_affectedByForces               = m_affectedByForces;
        if (p->m_isBall || p->m_isSpider)
            p->m_jumpBuffered                   = m_jumpBuffered;
        p->m_rotationSpeed                  = m_rotationSpeed;
        p->m_isBallRotating                 = m_isBallRotating;
        p->m_isBallRotating2                = m_isBallRotating2;
        p->m_stateRingJump                  = m_stateRingJump;
        p->m_touchedPad                     = m_touchedPad;
        p->m_isMoving                       = m_isMoving;
        p->m_holdingRight                   = m_holdingRight;
        p->m_holdingLeft                    = m_holdingLeft;
        p->m_isDashing                      = m_isDashing;
        p->m_leftPressedFirst               = m_leftPressedFirst;
        p->m_platformerMovingLeft           = m_platformerMovingLeft;
        p->m_platformerMovingRight          = m_platformerMovingRight;
        p->m_wasTeleported                  = m_wasTeleported;
        p->m_fixGravityBug                  = m_fixGravityBug;
        p->m_reverseSync                    = m_reverseSync;
        p->m_yVelocityBeforeSlope           = m_yVelocityBeforeSlope;
        p->m_dashX                          = m_dashX;
        p->m_dashY                          = m_dashY;
        p->m_dashAngle                      = m_dashAngle;
        p->m_dashStartTime                  = m_dashStartTime;
        p->m_slopeStartTime                 = m_slopeStartTime;
        p->m_justPlacedStreak               = m_justPlacedStreak;
        p->m_lastCollisionBottom            = m_lastCollisionBottom;
        p->m_lastCollisionTop               = m_lastCollisionTop;
        p->m_lastCollisionLeft              = m_lastCollisionLeft;
        p->m_lastCollisionRight             = m_lastCollisionRight;
        p->m_unk50C                         = m_unk50C;
        p->m_unk510                         = m_unk510;
        p->m_currentSlope2                  = m_currentSlope2;
        p->m_preLastGroundObject            = m_preLastGroundObject;
        p->m_slopeAngle                     = m_slopeAngle;
        p->m_slopeSlidingMaybeRotated       = m_slopeSlidingMaybeRotated;
        p->m_quickCheckpointMode            = m_quickCheckpointMode;
        p->m_collidedObject                 = m_collidedObject;
        p->m_lastGroundObject               = m_lastGroundObject;
        p->m_collidingWithLeft              = m_collidingWithLeft;
        p->m_collidingWithRight             = m_collidingWithRight;
        p->m_scaleXRelated2                 = m_scaleXRelated2;
        p->m_groundYVelocity                = m_groundYVelocity;
        p->m_yVelocityRelated               = m_yVelocityRelated;
        p->m_scaleXRelated3                 = m_scaleXRelated3;
        p->m_scaleXRelated4                 = m_scaleXRelated4;
        p->m_scaleXRelated5                 = m_scaleXRelated5;
        p->m_isCollidingWithSlope           = m_isCollidingWithSlope;
        p->m_unk669                         = m_unk669;
        p->m_currentPotentialSlope          = m_currentPotentialSlope;
        p->m_currentSlope                   = m_currentSlope;
        p->unk_584                          = unk_584;
        p->m_collidingWithSlopeId           = m_collidingWithSlopeId;
        p->m_slopeFlipGravityRelated        = m_slopeFlipGravityRelated;
        p->m_slopeAngleRadians              = m_slopeAngleRadians;
        p->m_rotateSpeed                    = m_rotateSpeed;
        p->m_speedMultiplier                = m_speedMultiplier;
        p->m_yStart                         = m_yStart;
        p->m_gravity                        = m_gravity;
        p->m_trailingParticleLife           = m_trailingParticleLife;
        p->m_gameModeChangedTime            = m_gameModeChangedTime;
        p->m_padRingRelated                 = m_padRingRelated;
        p->m_maybeIsFalling                 = m_maybeIsFalling;
        p->m_shouldTryPlacingCheckpoint     = m_shouldTryPlacingCheckpoint;
        p->m_playEffects                    = m_playEffects;
        p->m_isOnGround3                    = m_isOnGround3;
        p->m_lastSpiderFlipTime             = m_lastSpiderFlipTime;
        p->m_unkBool5                       = m_unkBool5;
        p->m_accelerationOrSpeed            = m_accelerationOrSpeed;
        p->m_snapDistance                   = m_snapDistance;
        p->m_ringJumpRelated                = m_ringJumpRelated;
        p->m_objectSnappedTo                = m_objectSnappedTo;
        p->m_maybeSpriteRelated             = m_maybeSpriteRelated;
        p->m_landParticlesAngle             = m_landParticlesAngle;
        p->m_landParticleRelatedY           = m_landParticleRelatedY;
        p->m_slopeRotation                  = m_slopeRotation;
        p->m_currentSlopeYVelocity          = m_currentSlopeYVelocity;
        p->m_unk3d0                         = m_unk3d0;
        p->m_blackOrbRelated                = m_blackOrbRelated;
        p->m_unk3e0                         = m_unk3e0;
        p->m_unk3e1                         = m_unk3e1;
        p->m_isCurrentSlopeTop              = m_isCurrentSlopeTop;
        p->m_collidedTopMinY                = m_collidedTopMinY;
        p->m_collidedBottomMaxY             = m_collidedBottomMaxY;
        p->m_collidedLeftMaxX               = m_collidedLeftMaxX;
        p->m_collidedRightMinX              = m_collidedRightMinX;
        p->m_wasJumpBuffered                = m_wasJumpBuffered;
        p->m_wasRobotJump                   = m_wasRobotJump;
        p->m_stateJumpBuffered              = m_stateJumpBuffered;
        p->m_stateRingJump2                 = m_stateRingJump2;
        p->m_touchedRing                    = m_touchedRing;
        p->m_touchedCustomRing              = m_touchedCustomRing;
        p->m_touchedGravityPortal           = m_touchedGravityPortal;
        p->m_maybeTouchedBreakableBlock     = m_maybeTouchedBreakableBlock;
        p->m_fallSpeed                      = m_fallSpeed;
        p->m_isOnSlope                      = m_isOnSlope;
        p->m_wasOnSlope                     = m_wasOnSlope;
        p->m_slopeVelocity                  = m_slopeVelocity;
        p->m_maybeUpsideDownSlope           = m_maybeUpsideDownSlope;
        p->m_reverseRelated                 = m_reverseRelated;
        p->m_maybeReverseSpeed              = m_maybeReverseSpeed;
        p->m_maybeReverseAcceleration       = m_maybeReverseAcceleration;
        p->m_xVelocityRelated2              = m_xVelocityRelated2;
        p->m_isOnGround2                    = m_isOnGround2;
        p->m_platformerVelocityRelated      = m_platformerVelocityRelated;
        p->m_maybeIsBoosted                 = m_maybeIsBoosted;
        p->m_scaleXRelatedTime              = m_scaleXRelatedTime;
        p->m_decreaseBoostSlide             = m_decreaseBoostSlide;
        p->m_isLocked                       = m_isLocked;
        p->m_controlsDisabled               = m_controlsDisabled;
        p->m_yVelocityRelated3              = m_yVelocityRelated3;
        p->m_defaultMiniIcon                = m_defaultMiniIcon;
        p->m_swapColors                     = m_swapColors;
        p->m_switchDashFireColor            = m_switchDashFireColor;
        p->m_followRelated                  = m_followRelated;
        p->m_unk838                         = m_unk838;
        p->m_stateOnGround                  = m_stateOnGround;
        p->m_stateUnk                       = m_stateUnk;
        p->m_stateNoStickX                  = m_stateNoStickX;
        p->m_stateNoStickY                  = m_stateNoStickY;
        p->m_stateUnk2                      = m_stateUnk2;
        p->m_stateBoostX                    = m_stateBoostX;
        p->m_stateBoostY                    = m_stateBoostY;
        p->m_maybeStateForce2               = m_maybeStateForce2;
        p->m_stateScale                     = m_stateScale;
        p->m_scaleXRelated                  = m_scaleXRelated;
        p->m_maybeHasStopped                = m_maybeHasStopped;
        p->m_xVelocityRelated               = m_xVelocityRelated;
        p->m_maybeGoingCorrectSlopeDirection = m_maybeGoingCorrectSlopeDirection;
        p->m_isSliding                      = m_isSliding;
        p->m_maybeSlopeForce                = m_maybeSlopeForce;
        p->m_isOnIce                        = m_isOnIce;
        p->m_physDeltaRelated               = m_physDeltaRelated;
        p->m_isOnGround4                    = m_isOnGround4;
        p->m_maybeSlidingTime               = m_maybeSlidingTime;
        p->m_maybeSlidingStartTime          = m_maybeSlidingStartTime;
        p->m_changedDirectionsTime          = m_changedDirectionsTime;
        p->m_slopeEndTime                   = m_slopeEndTime;
        p->m_isSlidingRight                 = m_isSlidingRight;
        p->m_maybeChangedDirectionAngle     = m_maybeChangedDirectionAngle;
        p->m_stateNoAutoJump                = m_stateNoAutoJump;
        p->m_stateDartSlide                 = m_stateDartSlide;
        p->m_stateHitHead                   = m_stateHitHead;
        p->m_stateFlipGravity               = m_stateFlipGravity;
        p->m_gravityMod                     = m_gravityMod;
        p->m_stateForce                     = m_stateForce;
        p->m_stateForceVector               = m_stateForceVector;
        p->m_somethingPlayerSpeedTime       = m_somethingPlayerSpeedTime;
        p->m_playerSpeedAC                  = m_playerSpeedAC;
        p->m_fixRobotJump                   = m_fixRobotJump;
        p->m_inputsLocked                   = m_inputsLocked;
        p->m_fallStartY                     = m_fallStartY;
        p->m_isGoingLeft                    = m_isGoingLeft;
        p->m_vehicleSize                    = m_vehicleSize;
        p->m_playerSpeed                    = m_playerSpeed;
        p->m_shipRotation                   = m_shipRotation;
        p->m_unkUnused3                     = m_unkUnused3;
        p->m_groundObjectMaterial           = m_groundObjectMaterial;
        p->m_dashRing                       = m_dashRing;
        p->m_isOutOfBounds                  = m_isOutOfBounds;
        p->m_isRobot                        = m_isRobot;
        p->m_isSpider                       = m_isSpider;
        p->m_isBall                         = m_isBall;
        p->m_isShip                         = m_isShip;
        p->m_isBird                         = m_isBird;
        p->m_isDart                         = m_isDart;
        p->m_isSwing                        = m_isSwing;
        p->m_isUpsideDown                   = m_isUpsideDown;
        p->m_isSideways                     = m_isSideways;
        p->m_isHidden                       = m_isHidden;
        for (size_t i = 1; i < m_holdingButtons.size(); i++)
            p->m_holdingButtons[i] = m_holdingButtons[i];
        p->m_lastFlipTime                   = m_lastFlipTime;
        p->m_hasGlow                       = m_hasGlow;
        p->m_dashFireFrame                  = m_dashFireFrame;
        p->m_positionX                     = m_positionX;
        p->m_positionY                     = m_positionY;
        p->setRotation(m_rotation);

        #ifndef GEODE_IS_ANDROID
        p->m_rotateObjectsRelated           = m_rotateObjectsRelated;
        p->m_potentialSlopeMap              = m_potentialSlopeMap;
        p->m_ringRelatedSet                 = m_ringRelatedSet;
        p->m_jumpPadRelated                 = m_jumpPadRelated;
        p->m_playerFollowFloats             = m_playerFollowFloats;
        p->m_currentRobotAnimation          = m_currentRobotAnimation;
        p->m_touchingRings->removeAllObjects();
        for (CCObject* obj : m_touchingRings)
            p->m_touchingRings->addObject(obj);
        #endif
    }
};

struct SupplementalPlayLayerState {
    GameObject* m_player1CollisionBlock = nullptr;
    GameObject* m_player2CollisionBlock = nullptr;
    double m_extraDelta = 0.0;
    int m_currentStep = 0;
    float m_unk3380 = 0.0f;
    int m_unk32d0 = 0;
    int m_unk32ec = 0;
    int m_commandIndex = 0;
    bool m_isPaused = false;

    #ifndef GEODE_IS_ANDROID
    gd::unordered_map<int, GameObjectPhysics> m_gameObjectPhysics;
    #endif

    SupplementalPlayLayerState() = default;

    SupplementalPlayLayerState(PlayLayer* pl) {
        if (!pl) return;
        m_player1CollisionBlock = pl->m_player1CollisionBlock;
        m_player2CollisionBlock = pl->m_player2CollisionBlock;
        m_extraDelta            = pl->m_extraDelta;
        m_currentStep           = pl->m_currentStep;
        m_unk3380               = pl->m_unk3380;
        m_unk32d0               = pl->m_unk32d0;
        m_unk32ec               = pl->m_unk32ec;
        m_commandIndex          = pl->m_gameState.m_commandIndex;
        m_isPaused              = pl->m_isPaused;

        #ifndef GEODE_IS_ANDROID
        m_gameObjectPhysics     = pl->m_gameState.m_gameObjectPhysics;
        #endif
    }

    void apply(PlayLayer* pl) const {
        if (!pl) return;
        pl->m_player1CollisionBlock = m_player1CollisionBlock;
        pl->m_player2CollisionBlock = m_player2CollisionBlock;
        pl->m_extraDelta            = m_extraDelta;
        pl->m_currentStep           = m_currentStep;
        pl->m_unk3380               = m_unk3380;
        pl->m_unk32d0               = m_unk32d0;
        pl->m_unk32ec               = m_unk32ec;
        pl->m_gameState.m_commandIndex = m_commandIndex;
        pl->m_isPaused              = m_isPaused;

        #ifndef GEODE_IS_ANDROID
        pl->m_gameState.m_gameObjectPhysics = m_gameObjectPhysics;
        #endif
    }
};
